[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Allow the /agent page to be embedded in your WordPress site via iframe (edit domain)
[[headers]]
  for = "/agent"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://www.yourwordpresssite.com https://yourdomain.com;"
    X-Content-Type-Options = "nosniff"
