[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  OPENAI_MODEL = "gpt-4o-mini"
  OPENAI_EMBEDDING_MODEL = "text-embedding-3-small"

[[headers]]
  for = "/agent"
  [headers.values]
    Content-Security-Policy = "frame-ancestors https://www.ryan.green https://ryan.green;"
    X-Content-Type-Options = "nosniff"
